//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apimex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empresas
    {
        public long id_Empresa { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Razon { get; set; }
        [Required]
        public string Telefono { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
